/*
 * generated by Xtext 2.42.0
 */
package org.farhan.dsl.cucumber.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCucumberScopeProvider extends DelegatingScopeProvider {
}
