name: Publish Sheep Dog Core Release

on:
  workflow_dispatch:
concurrency:
  group: sheep-dog-core
  cancel-in-progress: false
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-grammar:
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheep-dog-grammar'
    secrets: inherit

  sheepdogasciidoc-parent:
    needs: [sheep-dog-grammar]
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheepdogasciidoc.parent'
    secrets: inherit

  sheep-dog-asciidoc-api:
    needs: [sheepdogasciidoc-parent]
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheep-dog-asciidoc-api'
    secrets: inherit

  sheepdogcucumber-parent:
    needs: [sheep-dog-asciidoc-api]
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheepdogcucumber.parent'
    secrets: inherit

  sheep-dog-cucumber-gen:
    needs: [sheepdogcucumber-parent]
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheep-dog-cucumber-gen'
    secrets: inherit
